# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-lyrical-rcl
  version: 10.4.4
source:
  git: https://github.com/ros2-gbp/rcl-release.git
  tag: release/lyrical/rcl/10.4.4-1
  target_directory: ros-lyrical-rcl/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 20
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: The ROS client library common implementation. This package contains an API which builds on the ROS middleware API and is optionally built upon by the other ROS client libraries.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform != 'emscripten-wasm32'
      then:
        - ros-lyrical-mimick-vendor
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-lyrical-ament-cmake-gen-version-h
    - ros-lyrical-ament-cmake-ros
    - ros-lyrical-ament-lint-auto
    - ros-lyrical-ament-lint-common
    - ros-lyrical-launch
    - ros-lyrical-launch-testing
    - ros-lyrical-launch-testing-ament-cmake
    - ros-lyrical-libyaml-vendor
    - ros-lyrical-osrf-testing-tools-cpp
    - ros-lyrical-rcl-interfaces
    - ros-lyrical-rcl-logging-implementation
    - ros-lyrical-rcl-logging-interface
    - ros-lyrical-rcl-logging-noop
    - ros-lyrical-rcl-logging-spdlog
    - ros-lyrical-rcl-yaml-param-parser
    - ros-lyrical-rcutils
    - ros-lyrical-rmw
    - ros-lyrical-rmw-implementation
    - ros-lyrical-rmw-implementation-cmake
    - ros-lyrical-ros-environment
    - ros-lyrical-ros-workspace
    - ros-lyrical-rosidl-runtime-c
    - ros-lyrical-rosidl-runtime-cpp
    - ros-lyrical-service-msgs
    - ros-lyrical-test-msgs
    - ros-lyrical-tracetools
    - ros-lyrical-type-description-interfaces
    - ros2-distro-mutex 0.16.* lyrical_*
    - yaml
    - yaml-cpp
  run:
    - python
    - ros-lyrical-libyaml-vendor
    - ros-lyrical-rcl-interfaces
    - ros-lyrical-rcl-logging-implementation
    - ros-lyrical-rcl-logging-interface
    - ros-lyrical-rcl-logging-noop
    - ros-lyrical-rcl-logging-spdlog
    - ros-lyrical-rcl-yaml-param-parser
    - ros-lyrical-rcutils
    - ros-lyrical-rmw
    - ros-lyrical-rmw-implementation
    - ros-lyrical-ros-workspace
    - ros-lyrical-rosidl-runtime-c
    - ros-lyrical-service-msgs
    - ros-lyrical-tracetools
    - ros-lyrical-type-description-interfaces
    - ros2-distro-mutex 0.16.* lyrical_*
    - yaml
    - yaml-cpp
