# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-lyrical-image-geometry
  version: 4.1.0
source:
  git: https://github.com/ros2-gbp/vision_opencv-release.git
  tag: release/lyrical/image_geometry/4.1.0-3
  target_directory: ros-lyrical-image-geometry/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 20
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://www.ros.org/wiki/image_geometry
  license: Apache-2.0 OR BSD-3-Clause
  summary: '`image_geometry` contains C++ and Python libraries for interpreting images geometrically. It interfaces the calibration parameters in sensor_msgs/CameraInfo messages with OpenCV functions such as image rectification, much as cv_bridge interfaces ROS sensor_msgs/Image with OpenCV data types.'
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - deprecated
    - libgl-devel
    - libopencv
    - libopengl-devel
    - numpy
    - pip
    - py-opencv
    - python
    - ros-lyrical-ament-cmake-gtest
    - ros-lyrical-ament-cmake-pytest
    - ros-lyrical-ament-cmake-python
    - ros-lyrical-ament-cmake-ros
    - ros-lyrical-ros-environment
    - ros-lyrical-ros-workspace
    - ros-lyrical-sensor-msgs
    - ros2-distro-mutex 0.16.* lyrical_*
  run:
    - deprecated
    - libgl-devel
    - libopencv
    - libopengl-devel
    - py-opencv
    - python
    - ros-lyrical-ros-workspace
    - ros-lyrical-sensor-msgs
    - ros2-distro-mutex 0.16.* lyrical_*
