# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-lyrical-camera-ros
  version: 0.6.0
source:
  git: https://github.com/ros2-gbp/camera_ros-release.git
  tag: release/lyrical/camera_ros/0.6.0-3
  target_directory: ros-lyrical-camera-ros/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 20
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: MIT
  summary: node for libcamera supported cameras (V4L2, Raspberry Pi Camera Modules)
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - clang-format
    - numpy
    - pip
    - python
    - ros-lyrical-ament-cmake
    - ros-lyrical-ament-cmake-clang-format
    - ros-lyrical-ament-cmake-cppcheck
    - ros-lyrical-ament-cmake-flake8
    - ros-lyrical-ament-cmake-lint-cmake
    - ros-lyrical-ament-cmake-mypy
    - ros-lyrical-ament-cmake-pep257
    - ros-lyrical-ament-cmake-pyflakes
    - ros-lyrical-ament-cmake-xmllint
    - ros-lyrical-ament-lint-auto
    - ros-lyrical-camera-info-manager
    - ros-lyrical-cv-bridge
    - ros-lyrical-libcamera
    - ros-lyrical-rclcpp
    - ros-lyrical-rclcpp-components
    - ros-lyrical-ros-environment
    - ros-lyrical-ros-workspace
    - ros-lyrical-sensor-msgs
    - ros2-distro-mutex 0.16.* lyrical_*
  run:
    - python
    - ros-lyrical-ament-index-python
    - ros-lyrical-camera-info-manager
    - ros-lyrical-cv-bridge
    - ros-lyrical-image-view
    - ros-lyrical-libcamera
    - ros-lyrical-rclcpp
    - ros-lyrical-rclcpp-components
    - ros-lyrical-ros-workspace
    - ros-lyrical-ros2launch
    - ros-lyrical-sensor-msgs
    - ros2-distro-mutex 0.16.* lyrical_*
