# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-lyrical-class-loader
  version: 2.9.4
source:
  git: https://github.com/ros2-gbp/class_loader-release.git
  tag: release/lyrical/class_loader/2.9.4-3
  target_directory: ros-lyrical-class-loader/src/work
  patches:
    - patch/ros-lyrical-class-loader.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 20
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: http://ros.org/wiki/class_loader
  license: BSD-3-Clause
  summary: The class_loader package is a ROS-independent package for loading plugins during runtime and the foundation of the higher level ROS "pluginlib" library. class_loader utilizes the host operating system's runtime loader to open runtime libraries (e.g. .so/.dll files), introspect the library for exported plugin classes, and allows users to instantiate objects of these exported classes without the explicit declaration (i.e. header file) for those classes.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - console_bridge
    - numpy
    - pip
    - python
    - ros-lyrical-ament-cmake
    - ros-lyrical-ament-cmake-gtest
    - ros-lyrical-ament-lint-auto
    - ros-lyrical-ament-lint-common
    - ros-lyrical-console-bridge-vendor
    - ros-lyrical-rcpputils
    - ros-lyrical-ros-environment
    - ros-lyrical-ros-workspace
    - ros2-distro-mutex 0.16.* lyrical_*
  run:
    - console_bridge
    - python
    - ros-lyrical-console-bridge-vendor
    - ros-lyrical-rcpputils
    - ros-lyrical-ros-workspace
    - ros2-distro-mutex 0.16.* lyrical_*
