# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-lyrical-robot-state-publisher
  version: 3.5.5
source:
  git: https://github.com/ros2-gbp/robot_state_publisher-release.git
  tag: release/lyrical/robot_state_publisher/3.5.5-3
  target_directory: ros-lyrical-robot-state-publisher/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 20
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: BSD-3-Clause
  summary: This package take the joint angles of a robot as input, and publishes the 3D poses of the robot links to tf2, using a kinematic tree model of the robot.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - orocos-kdl
    - pip
    - python
    - ros-lyrical-ament-cmake
    - ros-lyrical-ament-cmake-gtest
    - ros-lyrical-ament-lint-auto
    - ros-lyrical-ament-lint-common
    - ros-lyrical-builtin-interfaces
    - ros-lyrical-geometry-msgs
    - ros-lyrical-kdl-parser
    - ros-lyrical-launch-ros
    - ros-lyrical-launch-testing-ament-cmake
    - ros-lyrical-rcl-interfaces
    - ros-lyrical-rclcpp
    - ros-lyrical-rclcpp-components
    - ros-lyrical-ros-environment
    - ros-lyrical-ros-workspace
    - ros-lyrical-sensor-msgs
    - ros-lyrical-std-msgs
    - ros-lyrical-tf2-ros
    - ros-lyrical-tf2-ros-py
    - ros-lyrical-urdf
    - ros2-distro-mutex 0.16.* lyrical_*
  run:
    - orocos-kdl
    - python
    - ros-lyrical-builtin-interfaces
    - ros-lyrical-geometry-msgs
    - ros-lyrical-kdl-parser
    - ros-lyrical-rcl-interfaces
    - ros-lyrical-rclcpp
    - ros-lyrical-rclcpp-components
    - ros-lyrical-ros-workspace
    - ros-lyrical-sensor-msgs
    - ros-lyrical-std-msgs
    - ros-lyrical-tf2-ros
    - ros-lyrical-urdf
    - ros2-distro-mutex 0.16.* lyrical_*
