# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-lyrical-py-trees-ros
  version: 2.4.0
source:
  git: https://github.com/ros2-gbp/py_trees_ros-release.git
  tag: release/lyrical/py_trees_ros/2.4.0-4
  target_directory: ros-lyrical-py-trees-ros/src/work

build:
  script: ${{ '$RECIPE_DIR/build_ament_python.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_python.bat' }}
  number: 20
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://py-trees-ros.readthedocs.io/en/release-1.2.x/
  repository: https://github.com/stonier/py_trees_ros
  license: BSD-3-Clause
  summary: ROS2 extensions and behaviours for py_trees.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - poetry-core
    - pytest
    - python
    - ros-lyrical-geometry-msgs
    - ros-lyrical-py-trees
    - ros-lyrical-py-trees-ros-interfaces
    - ros-lyrical-rcl-interfaces
    - ros-lyrical-rclpy
    - ros-lyrical-ros-environment
    - ros-lyrical-ros-workspace
    - ros-lyrical-ros2topic
    - ros-lyrical-sensor-msgs
    - ros-lyrical-std-msgs
    - ros-lyrical-std-srvs
    - ros-lyrical-tf2-ros-py
    - ros-lyrical-unique-identifier-msgs
    - ros2-distro-mutex 0.16.* lyrical_*
    - setuptools
  run:
    - python
    - ros-lyrical-geometry-msgs
    - ros-lyrical-py-trees
    - ros-lyrical-py-trees-ros-interfaces
    - ros-lyrical-rcl-interfaces
    - ros-lyrical-rclpy
    - ros-lyrical-ros-workspace
    - ros-lyrical-ros2topic
    - ros-lyrical-sensor-msgs
    - ros-lyrical-std-msgs
    - ros-lyrical-std-srvs
    - ros-lyrical-tf2-ros-py
    - ros-lyrical-unique-identifier-msgs
    - ros2-distro-mutex 0.16.* lyrical_*
