# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-lyrical-rosbag2-transport
  version: 0.33.3
source:
  git: https://github.com/ros2-gbp/rosbag2-release.git
  tag: release/lyrical/rosbag2_transport/0.33.3-1
  target_directory: ros-lyrical-rosbag2-transport/src/work
  patches:
    - patch/ros-lyrical-rosbag2-transport.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 20
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: Layer encapsulating ROS middleware to allow rosbag2 to be used with or without middleware
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-lyrical-ament-cmake-gmock
    - ros-lyrical-ament-cmake-ros
    - ros-lyrical-ament-index-cpp
    - ros-lyrical-ament-lint-auto
    - ros-lyrical-ament-lint-common
    - ros-lyrical-composition-interfaces
    - ros-lyrical-keyboard-handler
    - ros-lyrical-rclcpp
    - ros-lyrical-rclcpp-action
    - ros-lyrical-rclcpp-components
    - ros-lyrical-rcpputils
    - ros-lyrical-rcutils
    - ros-lyrical-rmw
    - ros-lyrical-rmw-implementation-cmake
    - ros-lyrical-ros-environment
    - ros-lyrical-ros-workspace
    - ros-lyrical-rosbag2-compression
    - ros-lyrical-rosbag2-compression-zstd
    - ros-lyrical-rosbag2-cpp
    - ros-lyrical-rosbag2-interfaces
    - ros-lyrical-rosbag2-storage
    - ros-lyrical-rosbag2-storage-default-plugins
    - ros-lyrical-rosbag2-test-common
    - ros-lyrical-test-msgs
    - ros2-distro-mutex 0.16.* lyrical_*
  run:
    - python
    - ros-lyrical-keyboard-handler
    - ros-lyrical-rclcpp
    - ros-lyrical-rclcpp-action
    - ros-lyrical-rclcpp-components
    - ros-lyrical-rcpputils
    - ros-lyrical-rcutils
    - ros-lyrical-rmw
    - ros-lyrical-ros-workspace
    - ros-lyrical-rosbag2-compression
    - ros-lyrical-rosbag2-cpp
    - ros-lyrical-rosbag2-interfaces
    - ros-lyrical-rosbag2-storage
    - ros2-distro-mutex 0.16.* lyrical_*
