# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-lyrical-rclcpp
  version: 32.0.0
source:
  git: https://github.com/ros2-gbp/rclcpp-release.git
  tag: release/lyrical/rclcpp/32.0.0-1
  target_directory: ros-lyrical-rclcpp/src/work
  patches:
    - patch/ros-lyrical-rclcpp.win.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 20
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  license: Apache-2.0
  summary: The ROS client library in C++.
extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - if: target_platform != 'emscripten-wasm32'
      then:
        - ros-lyrical-mimick-vendor
    - if: target_platform == 'emscripten-wasm32'
      then:
        - ros-lyrical-rosidl-default-generators
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - empy
    - numpy
    - pip
    - python
    - ros-lyrical-ament-cmake-gen-version-h
    - ros-lyrical-ament-cmake-google-benchmark
    - ros-lyrical-ament-cmake-gtest
    - ros-lyrical-ament-cmake-ros
    - ros-lyrical-ament-cmake-ros-core
    - ros-lyrical-ament-index-cpp
    - ros-lyrical-ament-lint-auto
    - ros-lyrical-ament-lint-common
    - ros-lyrical-builtin-interfaces
    - ros-lyrical-libstatistics-collector
    - ros-lyrical-performance-test-fixture
    - ros-lyrical-rcl
    - ros-lyrical-rcl-interfaces
    - ros-lyrical-rcl-logging-interface
    - ros-lyrical-rcl-yaml-param-parser
    - ros-lyrical-rcpputils
    - ros-lyrical-rcutils
    - ros-lyrical-rmw
    - ros-lyrical-rmw-implementation-cmake
    - ros-lyrical-ros-environment
    - ros-lyrical-ros-workspace
    - ros-lyrical-rosgraph-msgs
    - ros-lyrical-rosidl-default-generators
    - ros-lyrical-rosidl-dynamic-typesupport
    - ros-lyrical-rosidl-runtime-c
    - ros-lyrical-rosidl-runtime-cpp
    - ros-lyrical-rosidl-typesupport-c
    - ros-lyrical-rosidl-typesupport-cpp
    - ros-lyrical-statistics-msgs
    - ros-lyrical-test-msgs
    - ros-lyrical-tracetools
    - ros2-distro-mutex 0.16.* lyrical_*
  run:
    - python
    - ros-lyrical-ament-index-cpp
    - ros-lyrical-builtin-interfaces
    - ros-lyrical-libstatistics-collector
    - ros-lyrical-rcl
    - ros-lyrical-rcl-interfaces
    - ros-lyrical-rcl-logging-interface
    - ros-lyrical-rcl-yaml-param-parser
    - ros-lyrical-rcpputils
    - ros-lyrical-rcutils
    - ros-lyrical-rmw
    - ros-lyrical-ros-workspace
    - ros-lyrical-rosgraph-msgs
    - ros-lyrical-rosidl-dynamic-typesupport
    - ros-lyrical-rosidl-runtime-c
    - ros-lyrical-rosidl-runtime-cpp
    - ros-lyrical-rosidl-typesupport-c
    - ros-lyrical-rosidl-typesupport-cpp
    - ros-lyrical-statistics-msgs
    - ros-lyrical-tracetools
    - ros2-distro-mutex 0.16.* lyrical_*
